//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Establishment_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Affectation()
        {
            this.Seance = new HashSet<Seance>();
        }
    
        public int numAff { get; set; }
        public Nullable<int> numGrp { get; set; }
        public string numFlr { get; set; }
        public Nullable<int> numMdl { get; set; }
        public Nullable<int> numFrm { get; set; }
        public Nullable<System.DateTime> dateAff { get; set; }
    
        public virtual Formateur Formateur { get; set; }
        public virtual Groupe Groupe { get; set; }
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seance { get; set; }
    }
}
