//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Establishment_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFM_Planification
    {
        public int numMdl { get; set; }
        public string numFlr { get; set; }
        public int numGrp { get; set; }
        public Nullable<System.DateTime> date_prevue { get; set; }
        public Nullable<System.DateTime> date_efective { get; set; }
    
        public virtual Groupe Groupe { get; set; }
        public virtual Module Module { get; set; }
    }
}
