//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Establishment_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formateur()
        {
            this.Affectation = new HashSet<Affectation>();
        }
    
        public int numfrm { get; set; }
        public string matricule { get; set; }
        public string cin { get; set; }
        public string nomfrm { get; set; }
        public string prenomfrm { get; set; }
        public Nullable<System.DateTime> dateN { get; set; }
        public Nullable<System.DateTime> dateEmbauche { get; set; }
        public string grade { get; set; }
        public string statut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectation { get; set; }
    }
}
