//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Establishment_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFP_FinalEntities : DbContext
    {
        public EFP_FinalEntities()
            : base("name=EFP_FinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affectation> Affectation { get; set; }
        public virtual DbSet<EFM_Planification> EFM_Planification { get; set; }
        public virtual DbSet<Filiere> Filiere { get; set; }
        public virtual DbSet<Formateur> Formateur { get; set; }
        public virtual DbSet<Groupe> Groupe { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Seance> Seance { get; set; }
        public virtual DbSet<Stagaire> Stagaire { get; set; }
    }
}
