//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Establishment_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Affectation = new HashSet<Affectation>();
            this.EFM_Planification = new HashSet<EFM_Planification>();
        }
    
        public int numMdl { get; set; }
        public string numflr { get; set; }
        public string anneeMdl { get; set; }
        public string nomMdl { get; set; }
        public Nullable<int> MH { get; set; }
        public Nullable<int> coeficientMdl { get; set; }
        public string semestreMdl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFM_Planification> EFM_Planification { get; set; }
        public virtual Filiere Filiere { get; set; }
    }
}
